AWSTemplateFormatVersion: '2010-09-09'
Description: Cognito User Pool and Client

Resources:
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: devsecops-user-pool
      AutoVerifiedAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false
          RequireUppercase: true
      Schema:
        - Name: email
          AttributeDataType: String
          Mutable: true
          Required: true
        - Name: name
          AttributeDataType: String
          Mutable: true
          Required: true

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: devsecops-client
      UserPoolId: !Ref UserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_USER_SRP_AUTH
        - ALLOW_ADMIN_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      SupportedIdentityProviders:
        - COGNITO
      # Allow callback to local/ALB - To be updated or wildcarded
      # For demo using a placeholder that needs to be updated with actual ALB DNS or just a dummy
      CallbackURLs:
        - https://example.com/oauth2/idpresponse
      LogoutURLs:
        - https://example.com
      AllowedOAuthFlows:
        - code
      AllowedOAuthScopes:
        - email
        - openid
        - profile
      AllowedOAuthFlowsUserPoolClient: true

  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !ImportValue DevSecOps-CognitoDomainPrefix
      UserPoolId: !Ref UserPool

Outputs:
  UserPoolId:
    Value: !Ref UserPool
    Export:
      Name: DevSecOps-UserPoolId
  UserPoolClientId:
    Value: !Ref UserPoolClient
    Export:
      Name: DevSecOps-UserPoolClientId
  UserPoolDomain:
    Value: !Ref UserPoolDomain
    Export:
      Name: DevSecOps-UserPoolDomain
